version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: callMeAnything!
          command: |
            echo "hello world"
            # . venv/bin/activate
            # python manage.py test


