version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1

    working_directory: ~/repo

    steps:
      - checkout

    - add_ssh_keys:
        fingerprints:
          - "d6:e8:8b:e5:71:41:86:c3:6b:cc:6f:2c:e2:1b:0b:2e"

      - run:
          name: callMeAnything!
          command: |
            echo "hello world"
            # . venv/bin/activate
            # python manage.py test


